# Upstream image
## ------
FROM

# Metadata
## ------
LABEL service.author=""
LABEL service.name=""
LABEL service.tag=""
LABEL service.upstream.repository=""
LABEL service.upstream.service=""
LABEL service.upstream.version=""
LABEL service.upstream.tag=""

# Service
## ------
EXPOSE
